import { useEffect, useState } from 'react'
import type { FormEvent } from 'react'

type Session = { access_token: string; refresh_token?: string; expires_at?: number }
type Workspace = { id: string; name: string; type: 'personal' | 'team' }
type SwitchRequest = { client_name: string; current_workspace?: Workspace | null; requested_workspace_id?: string | null; expires_at: string; workspaces: Workspace[] }

const API_BASE = import.meta.env.VITE_API_URL?.trim() || 'https://api.ledgerworkspace.com'
const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL?.trim() || ''
const SUPABASE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY?.trim() || import.meta.env.VITE_SUPABASE_ANON_KEY?.trim() || ''
const clearLegacySession = () => window.localStorage.removeItem('ledger-web-auth-session')
const readOAuthSession = () => { const hash = new URLSearchParams(window.location.hash.replace(/^#/, '')); const token = hash.get('access_token'); if (!token) return null; const session = { access_token: token, refresh_token: hash.get('refresh_token') || undefined, expires_at: Number(hash.get('expires_at') || 0) || undefined }; clearLegacySession(); window.history.replaceState({}, document.title, `${window.location.pathname}${window.location.search}`); return session }
const authRequest = async (path: string, body: Record<string, string>) => { const response = await fetch(`${SUPABASE_URL}/auth/v1/${path}`, { method: 'POST', headers: { 'Content-Type': 'application/json', apikey: SUPABASE_KEY }, body: JSON.stringify(body) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload?.msg || payload?.error_description || 'Ledger sign-in failed.'); return payload as Session }

export function McpWorkspaceSwitchPage({ sessionId, code }: { sessionId: string; code: string }) {
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [session, setSession] = useState<Session | null>(null); const [request, setRequest] = useState<SwitchRequest | null>(null); const [workspaceId, setWorkspaceId] = useState(''); const [state, setState] = useState<'loading' | 'sign_in' | 'ready' | 'busy' | 'done' | 'error'>('loading'); const [error, setError] = useState('')
  const configured = Boolean(SUPABASE_URL && SUPABASE_KEY)
  const load = async (token: string) => { const response = await fetch(`${API_BASE}/api/mcp/workspace-switches/${encodeURIComponent(sessionId)}`, { headers: { Authorization: `Bearer ${token}` } }); const payload = await response.json().catch(() => ({})); if (response.status === 401) { clearLegacySession(); setSession(null); setState('sign_in'); setError('Your Ledger session expired. Sign in again.'); return } if (!response.ok) throw new Error(payload?.error || 'This workspace switch request is invalid or expired.'); setRequest(payload); setWorkspaceId(payload.requested_workspace_id || payload.workspaces?.[0]?.id || ''); setState('ready') }
  useEffect(() => { const next = readOAuthSession(); clearLegacySession(); setSession(next); if (!configured) { setError('Ledger web authentication is not configured.'); setState('error'); return } if (!next) { setState('sign_in'); return } void load(next.access_token).catch((caught) => { setError(caught instanceof Error ? caught.message : 'Could not load this request.'); setState('error') }) }, [configured, sessionId])
  const signIn = async (event: FormEvent) => { event.preventDefault(); setState('busy'); setError(''); try { const next = await authRequest('token?grant_type=password', { email: email.trim(), password }); setSession(next); await load(next.access_token) } catch (caught) { setError(caught instanceof Error ? caught.message : 'Ledger sign-in failed.'); setState('sign_in') } }
  const google = () => { if (configured) window.location.assign(`${SUPABASE_URL}/auth/v1/authorize?provider=google&redirect_to=${encodeURIComponent(window.location.href.split('#')[0])}&apikey=${encodeURIComponent(SUPABASE_KEY)}`) }
  const approve = async () => { if (!session || !workspaceId) return; setState('busy'); setError(''); try { const response = await fetch(`${API_BASE}/api/mcp/workspace-switches/${encodeURIComponent(sessionId)}/approve`, { method: 'POST', headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${session.access_token}` }, body: JSON.stringify({ verification_code: code, workspace_id: workspaceId }) }); const payload = await response.json().catch(() => ({})); if (!response.ok) throw new Error(payload?.error || 'Could not switch the workspace.'); setState('done') } catch (caught) { setError(caught instanceof Error ? caught.message : 'Could not switch the workspace.'); setState('error') } }
  if (state === 'loading') return null
  return <main className="min-h-dvh bg-ledger-bg px-6 py-12 text-ledger-text"><section className="mx-auto flex min-h-[calc(100dvh-6rem)] w-full max-w-[460px] items-center justify-center"><div className="w-full rounded-[28px] border border-(--ledger-border-subtle) bg-(--ledger-surface-card) p-7 shadow-[0_18px_60px_rgba(15,23,42,0.08)]"><img src="/assets/logos/logo.svg" alt="Ledger" className="h-9 w-9" /><p className="mt-5 text-[13px] font-medium text-ledger-text-muted">Ledger workspace access</p><h1 className="mt-2 text-[26px] font-semibold tracking-[-0.04em]">Switch {request?.client_name || 'MCP'} workspace</h1>{state === 'sign_in' ? <><p className="mt-3 text-[15px] leading-7 text-ledger-text-muted">Sign in to choose the workspace this connection can access.</p><form className="mt-7 space-y-3" onSubmit={(event) => void signIn(event)}><input required type="email" placeholder="Email" value={email} onChange={(event) => setEmail(event.target.value)} className="ledger-field h-11 w-full border border-(--ledger-border-subtle) bg-(--ledger-bg) px-4 text-[15px]" /><input required type="password" placeholder="Password" value={password} onChange={(event) => setPassword(event.target.value)} className="ledger-field h-11 w-full border border-(--ledger-border-subtle) bg-(--ledger-bg) px-4 text-[15px]" /><button className="ledger-button h-11 w-full bg-ledger-accent text-[15px] font-semibold text-white" type="submit">Continue</button><button className="ledger-button h-11 w-full border border-(--ledger-border-subtle) text-[15px] font-semibold" type="button" onClick={google}>Continue with Google</button></form></> : state === 'ready' && request ? <><p className="mt-3 text-[15px] leading-7 text-ledger-text-muted">Choose the workspace this MCP connection should use. Existing read/write permissions remain subject to that workspace’s Ledger role.</p><div className="mt-6 rounded-2xl bg-(--ledger-surface-muted) p-4"><p className="text-xs font-medium text-ledger-text-muted">Current workspace</p><p className="mt-1 text-[15px]">{request.current_workspace?.name || 'Unavailable'}</p><p className="mt-4 text-xs font-medium text-ledger-text-muted">New workspace</p><select value={workspaceId} onChange={(event) => setWorkspaceId(event.target.value)} className="ledger-field mt-2 h-11 w-full border border-(--ledger-border-subtle) bg-(--ledger-surface-card) px-3 text-[15px]">{request.workspaces.map((workspace) => <option key={workspace.id} value={workspace.id}>{workspace.name}</option>)}</select></div><button type="button" disabled={!workspaceId} onClick={() => void approve()} className="ledger-button mt-7 h-11 w-full bg-ledger-accent text-[15px] font-semibold text-white disabled:opacity-50">Approve workspace switch</button></> : <p className="mt-3 text-[15px] leading-7 text-ledger-text-muted">Workspace switched. Return to your MCP client and retry the request.</p>}{error && <p className="mt-5 text-sm leading-6 text-red-600" role="alert">{error}</p>}</div></section></main>
}
